### ISSUE TITLE
Time, area and weather data not in data download from iRecord

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#123]
Hi, perhaps one for @DavidRoy ? I've just run a download from iRecord for the dummy timed count I did yesterday and the download spreadsheet has no data for the duration, start time or any of the weather variables.

**Comment by RichardFoxBC** [comment]
Hi @DavidRoy - has this been resolved?

**Comment by DavidRoy** [comment]
No, we won't be able to work on this till after the end of March.  I also think the extra survey information is of most use to the UKBMS to a key additional requirement is integrating within UKBMS reports?

Let's leave this issue open but we might raise other related issues

**Comment by DavidRoy** [comment]
@RichardFoxBC were the columns not present in the download, or the values not populated.  The configuration for obtaining all the survey-species attributes is to explicitly select the survey, e.g. this configuration
![irb single-species timed count](https://user-images.githubusercontent.com/2699478/161537842-c27acffc-d127-4eff-89c4-c6a2ee3317f4.png)

**Comment by RichardFoxBC** [comment]
Hi David,

The columns are there but are empty. Here is a download of a dummy single-species timed count that I just created
[download-624afdbf9ceee5.99147904.csv](https://github.com/NERC-CEH/irecord-butterflies-app/files/8410452/download-624afdbf9ceee5.99147904.csv)
.

**Comment by DavidRoy** [comment]
Thanks for confirming.
@johnvanbreda - can you pick this issue up, following our meeting yesterday. The missing attributes are shown via the record view, e.g. 
https://irecord.org.uk/record-details?occurrence_id=24818631

but missing from downloads.  Perhaps the ElasticSearch is not picking up all the sample/sub-sample attributes?

**Comment by johnvanbreda** [comment]
I've confirmed that for the example record, the Elasticsearch index is correctly populated. The download is also correct for the attributes that are at the sample or occurrence level, but the code which automatically includes sample attribute columns for the selected survey does not utilise the attribute values stored in the parent sample, which is why the columns are blank.

Now looking at the code...

**Comment by johnvanbreda** [comment]
@RichardFoxBC can you try now please?

**Comment by RichardFoxBC** [comment]
Hi @johnvanbreda - many thanks for looking at this. It is getting there. Still missing is %cloud, which needs to be calculated from the % sunshine value collected by the app (i.e. % cloud = 100 - % sun). By the way @kazlauskis I'm not sure that the app is correctly gathering % sun from the weather api - it seems to always be set at 1% in the tests that I've carried out.

Also missing are any abundance data. The way that the single-species timed count mode works means that all individual occurrences must be of 1 seen, but this should still be in the download otherwise the user of the downloaded data won't know.

**Comment by DavidRoy** [comment]
@kazlauskis it makes sense for you to submit both the %cloud and %sun figures from the app, rather than have a process at the warehouse end.  I'll raise a separate issue for this

@kazlauskis for the abundance value of 1, I think this is also something for the app data submission.  You do this for the ButterflyCount survey but not the iRecord Butterflies single-species timed count survey?  I'll also raise a separate issue for this

**Comment by kazlauskis** [comment]
@RichardFoxBC we have checked your test records that you've send with the 1% sun and these have been captured in a similar place at similar time. Looking at the historical weather data this figure is right.
