### ISSUE TITLE
App use of location

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#126]
When I first opened the single species timed count mode I got the attached message. Two things about this - first can we change the title please from "Time survey" to "Timed count". Second, is it necessary to have the option to Always Allow? Why would we want our app to always be using a person's location??
![IMG_9379](https://user-images.githubusercontent.com/36193573/158146594-80aba7bc-81e5-43e4-b8bb-ed77665a5da8.PNG)

**Comment by kazlauskis** [comment]
@Vilius-Stankaitis change the popup title please from "Time survey" to "Timed count".

@RichardFoxBC this is a question about allowing the app to track your movement even if you have locked your device.

**Comment by DavidRoy** [comment]
"this is a question about allowing the app to track your movement even if you have locked your device"
@RichardFoxBC this is definitely needed as phones will 'go to sleep' on long timed counts
@kazlauskis should we say something in the pop-up text to explain this, otherwise most people will select 'only when using'?

**Comment by kazlauskis** [comment]
@DavidRoy Sure, what would you like the popup message to say?

**Comment by DavidRoy** [comment]
Change "Allow background geolocation to set your survey transect" to
"Please select 'Change to allow always allow' to enable an accurate location for your sightings and time counts, even when your phone is locked or asleep."
