### ISSUE TITLE
Finalise list of credits

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#17]
list of photographers of images used

BC staff who have contributed to content, e.g. species cut-outs

**Comment by RichardFoxBC** [comment]
Under the main list for input into the app, I'm not sure that we need Katie. I don't think she was really involved much in the development of this new app. We should add Anthony McCluskey to this list.

Andrew Cooper and Anthony McCluskey were responsible for the cut-outs so it would be nice to acknowledge that.

Additional photographers that need to be added to the photographers list are:
Adam Gor
John Murray
Anthony Pope
Peter Withers

Ideally, the photographer list would be alphabetical by surname rather than first name please.

**Comment by DavidRoy** [comment]
@kazlauskis re-opening as I remembered we need to acknowledge Peter Eeles more fully.  Please add the following.

"We are extremely grateful to Peter Eeles who has generously shared images of immature stages of butterflies for use within this application.  To learn more about butterfly life-cycles please visit https://www.butterflylifecycles.com or refer to Peter's book: Eeles, P. (2019) _Life Cycles of British and Irish Butterflies_. Pisces Publications, Newbury."

@RichardFoxBC to confirm credit for maps etc

**Comment by RichardFoxBC** [comment]
Please add (Butterfly Conservation) after Anthony's name.

Also please add the following text below the text re Peter Eeles:
"We are also extremely grateful to Chris Manley who prepared the species distribution maps used in this app. His book British and Irish Moths. A Photographic Guide (third edition) by Bloomsbury provides a great identification guide to moths."
