### ISSUE TITLE
Terms of use out of date

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-butterflies-app#3]
On the app's registration page there is a link to "iRecord Terms and Conditions", but these are coded into the app and do not link to the 'live' terms of use on the website. The app terms are now out of line with the website.

**Comment by kazlauskis** [comment]
Can I just point to the new iRecord site T&Cs and privacy policy in the app?

**Comment by kazlauskis** [comment]
From discussions it will be a link.

**Comment by RichardFoxBC** [comment]
Just reaquainting myself with the iRecord T&Cs. 

David - what downsides for BC can you see from us just going with the simplest option of linking to the iRecord terms of use etc? 
1) I guess that BC would not be able to repatriate to County Recorders the email addresses of recorders using the app? Of course, if a County Recorder engages properly with iRecord as a verifyer then this isn't an issue, but for those that haven't yet or don't want to, this lack of communication route may lead them to simply ignore all repatriated iRecord records. Even more likely that this is the response if and when we add in day-flying moths and interact with the County Moth Recorders!

2) Would BC be able to email app users directly under legitimate interest? Is this what we effectively did a couple of weeks ago when we emailed everyone re the development of the new app?

3) Would it be possible to introduce an opt-in button somewhere in the registration process (for new users) and log in process (for existing iRecord users) so that BC could legitimately add app users to our mailing lists for e-newsletters such as All Aflutter and even for fundraising purposes etc.?

**Comment by DavidRoy** [comment]
To confirm.  The existing iRecord privacy/t&cs allow #1 and #2.  Therefore the extra complexity of #3 is not needed.
@RichardFoxBC please close if you are ok with this
