### ISSUE TITLE
Check stats reporting

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#39]
Please can you check the stats reporting - the app stats page is saying that I've seen 8 species in 2021, but I think I've only seen 7. Is it accidentally including a non-butterfly species record?

**Comment by kazlauskis** [comment]
@johnvanbreda could you please have a look at this?

**Comment by RichardFoxBC** [comment]
As far as I am aware I have currently recorded 9 butterfly species in 2021 but the app statistics page is showing 11

**Comment by johnvanbreda** [comment]
@kazlauskis I think this problem is because the app is submitting records both against the UKSI list and the EBMS list. For example, record 20169080 of Gonepteryx rhamni uses the UKSI version of this taxon, record 20138043 uses the UKBMS version of the taxon. As resolving taxa on names doesn't really work, we use the number of different accepted name keys from the terms to resolve the number of species - but these are different lists which use different keys. In effect, Indicia has no way of knowing for sure they are supposed to be the same thing.

Is there a reason why records have been submitted against the EBMS list?

**Comment by kazlauskis** [comment]
Thanks, we have initially used the EBMS ids and @DavidRoy has changed it to a different one (UKSI?) a few weeks ago. Does this mean that as long as we keep it UKSI-only then this shouldn't be an issue? If so then please close the ticket.

**Comment by johnvanbreda** [comment]
@kazlauskis that's correct, for data going forward. Not sure if I should close this since the data Richard entered earlier than the switchover point will be wrong.

**Comment by kazlauskis** [comment]
I think this affects only Richard and it is only 2 (?) records. Shall we reassign the taxa in those records? Do you know which occurrences are these? I could probably use some iRecord form to reattach these to the UKSI species.

**Comment by DavidRoy** [comment]
It also affects 1-2 of my records?

**Comment by RichardFoxBC** [comment]
Happy for you to reassign the species ID of my records that are affected. Or, if you can tell me which they are, I can make a note of the details and then reenter them after you've made any necessary changes. Either way we need to get this sorted out before other people start to test the app.

**Comment by johnvanbreda** [comment]
I've corrected the records to use UKSI. It will take an hour or so to be reflected in the reports.

**Comment by kazlauskis** [comment]
@RichardFoxBC please close this ticket once you have checked that the stats are correct in the app.
