### ISSUE TITLE
Update likelihood filters within app

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#69]
Using latest BNM dataset

Replace 'old' versions in the app

Small task for KK

**Comment by RichardFoxBC** [comment]
Use BNM data for 2005-2019 for new rules about what is in your 10km squares

**Comment by DavidRoy** [comment]
@RichardFoxBC to provide example issues to check, e.g. Dingy Skipper missing from lists
@DavidRoy to supply updated geographic filter file to @kazlauskis by 5th July at latest
Time filters to be updated at later date

**Comment by RichardFoxBC** [comment]
Issues from testing the new geographic probabilities supplied by @DavidRoy 
Dingy Skipper missing from ST60
White Admiral should be included in flying now lists for this week, I would have thought e.g. in SX86. Surprised that Small Heath also not listed as flying now in SX86. There were plenty around at a local site on Saturday (26 June).

**Comment by RichardFoxBC** [comment]
I was surprised to find at the weekend that Silver-washed Fritillary appeared in the "Species not recorded from your area" list in the beta version of the app. I am in SX86 and there are plenty of BNM records in our 2005-2019 date period in this square. Please can you investigate why it is not appearing in one of the "in your area" lists?

**Comment by kazlauskis** [comment]
I'll look into this.

**Comment by kazlauskis** [comment]
I have found 4 species that have cut-off IDs in the probability docs:
```
SmallPearlBorderedFri
SilverWashedFritillar
PearlBorderedFritilla
QueenOfSpainFritillar
```

I have corrected these now but it would be good to fix the probability data (weekly and geospacial) scripts to not trim the IDs and keep these full length @DavidRoy 

The IDs here aren't new to this Beta update and so this issue is in the public app. The fix should come out when we release the Beta.

@RichardFoxBC Also, what is the correct name of the `Polyommatus coridon` - Chalkhill Blue or Chalk Hill Blue?

**Comment by DavidRoy** [comment]
Well done on finding this.  These short-hand names came from the old app but I agree that truncated names are not helpful.  I'll include the IDs in future versions

**Comment by RichardFoxBC** [comment]
Is it the truncated names then that is causing these species to be put into the wrong lists in the app?

Polyommatus coridon is Chalk Hill Blue

**Comment by kazlauskis** [comment]
> Is it the truncated names then that is causing these species to be put into the wrong lists in the app?

Yes. I didn't see that some species didn't have the full IDs when developing the app. In the old app there might have been some extra mapping added or similar.

@DavidRoy would it be possible to use `ChalkHillBlue` instead of `ChalkhillBlue` in the probability files? This would help me to keep the lookup code consistent across all the species.

**Comment by RichardFoxBC** [comment]
That's good then. Another problem removed!
