### ISSUE TITLE
Show thanks after a survey upload

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#75]
Say something nice to the user after a survey is uploaded. We could detect when the user is uploading multiple surveys and show the message only once.

**Comment by kazlauskis** [comment]
This is an example message that is currently shown to a user in a FIT Count app:

<img width="365" alt="Screenshot 2021-05-13 at 15 02 18" src="https://user-images.githubusercontent.com/7383162/118137000-9b166a00-b3fc-11eb-802a-5f9398bd91cb.png">

**Comment by RichardFoxBC** [comment]
@kazlauskis @DavidRoy I like this idea and Karolis has a little time to potentially fit this into version 2. I suggest that rather than having the thank you after every upload, which could get a bit tedious if you are doing a lot of recording, perhaps we could have it pop up after the submission of each 10, 25, 50, 100, 200 records each calendar year? The message could then say 

"Thank you for submitting your butterfly records - every record helps us to conserve the UK's butterflies.

You have now uploaded XXX records since the start of 2021, comprising XX butterfly species"

Any thoughts?

best wishes
Richard

**Comment by kazlauskis** [comment]
> You have now uploaded XXX records since the start of 2021, comprising XX butterfly species

@RichardFoxBC @DavidRoy showing the stats below might not be straightforward. The database that iRecord uses for reports updates only every 15 minutes (data is cached) - this is currently used for the figures that you see when you open the user statistics page.

We could use the same report data when showing the info messages but it would be misleading to see old stats when you know you've just uploaded a new species. Alternative would be to use local records for these particular thanks messages. This would be instantaneous to calculate in the app and wouldn't need the use of the cached server reports. The disadvantage of this would be that the figures would only come from your current device data and if the user deletes any records or reinstalls the app then the statistics would be flawed unless phrased differently, also this wouldn't represent any other records coming from user's other devices.

Any thoughts?

**Comment by DavidRoy** [comment]
@kazlauskis I think we should use the iRecord cache numbers, but give a message to explain that this only includes uploaded records and will not include those very recently uploaded.

This is the best option for encouraging uploads imho

**Comment by kazlauskis** [comment]
OK, thanks. How would you like to rephrase the message? maybe something simple like this:

"You have now uploaded XXX records since the start of 2021, comprising XX butterfly species (updated 15mins ago)"

**Comment by RichardFoxBC** [comment]
@kazlauskis We definitely shouldn't use the locally cached data on the device. So we can only really use the data reports from the iRecord database. In this case, I think we should exclude the number of species as that is the thing that users will notice as being out of date. I assume we are going with my suggestion of only putting this message up after 'milestone' numbers of records, rather than after every submission? If so, the message can be themed around that perhaps with a series of stars that reflect the number of records the person has submitted e.g. one star after the first 25 records in a calendar year, two stars, after the first 50, three stars after the first 100, four stars after 500, and five stars after 1000? 

The message could read:

STAR ICON
"25 RECORDS SUBMITTED
You have now uploaded 25 or more butterfly records since the start of 202X, many thanks!
Every record you submit helps us to conserve the UK's butterflies."

**Comment by DavidRoy** [comment]
that works for me (say '15 minutes ago' if space), but @RichardFoxBC to confirm

**Comment by RichardFoxBC** [comment]
I'm not sure that the "15 mins ago" is needed. There might have been a long delay between the user submitting their 25th record (which would not prompt the message) and then submitting their 26th (which would prompt the message). In fact, now that I think about it, the message will only ever be prompted on the next upload that occurs >15 mins after the one that took them to the 25, 50, 100 etc. threshold. (If I've understood correctly how this will work!). So we can amend the message to read:

STAR ICON
"OVER 25 RECORDS SUBMITTED
You have now uploaded over 25 butterfly records since the start of 202X, many thanks!
Every record you submit helps us to conserve the UK's butterflies."

**Comment by DavidRoy** [comment]
I agree, making this milestone based keeps this simpler.

Should we also have a 'Milestones' page?  A nudge towards gamification and reward 'badges'

**Comment by RichardFoxBC** [comment]
Perhaps not yet?

**Comment by kazlauskis** [comment]
I understand you want these 'milestone' triggers to be based on the server stats and not the user local records too, is that right?

**Comment by RichardFoxBC** [comment]
Yes absolutely. Given the problems with the local cache that you outlined in an earlier message, I don't think we should use them at all.

**Comment by kazlauskis** [comment]
OK. There might be a scenario where a user creates 100 records (pending) and taps upload all, it might take a minute or two for these all to reach the server and the server statistics would only be updated some time after that. In such a case after all the 100 records reached the server no popup thanks message would be shown. Only after some 15 mins have passed and a new record (which would count as 101) is uploaded we would show a 4 star thank you. Sounds OK?

**Comment by RichardFoxBC** [comment]
Yes that sounds OK. My understanding/assumption is that the thank-you pop-up will only appear after a record has been uploaded i.e. it won't just appear spontaneously e.g. when the app is opened.

If that's correct, then the pop-up for a particular milestone will only ever appear when the user submits a record >15 mins after the record that reached the milestone threshold. Thus the actual number of submitted records (including the ones that the user has just uploaded, but which haven't yet been counted in the iRecord database report) will always be more than the milestone, which is why I've suggested the revised phrasing.
